### PR TITLE
Update index.d.ts

### PR DESCRIPTION
**Pull request by kbsanders**
Updated with API documentation and links.
Added anything I saw missing.
Changed syntax of class and interface function definitions:
```
// before
foo: () => boolean;
// after
foo(): boolean;
```

### CODE REVIEW

**Comment by albinmedoc** [comment]
This should be merged

**Comment by albinmedoc** [comment]
Please release a new version, https://www.npmjs.com/package/uxp-types

**Comment by thejustinwalsh** [comment]
I thought I had GitHub actions automation on this repo, turns out I don't. Will release it shortly.

**Comment by thejustinwalsh** [comment]
@albinmedoc done

**Comment by albinmedoc** [comment]
@thejustinwalsh Super! Thank you

**Pull request merged**
